apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Prorata-ai/agrocd-test.git
    targetRevision: HEAD
    path: harry
  destination:
    server: https://supervisors-3hfs9ocb.hcp.eastus.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 