# Crossplane resource definition
apiVersion: database.azure.crossplane.io/v1beta1
kind: MySQLServer
metadata:
  name: my-database
spec:
  forProvider:
    location: "East US"
    resourceGroupName: "my-resource-group"
    sku:
      name: "GP_Gen5_2"
    version: "5.7"
    administratorLogin: "admin"
    administratorPasswordSecretRef:
      name: db-password
      namespace: crossplane-system
---
# ArgoCD Application to manage the database
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: HEAD
    path: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 